### PR TITLE
Updated dependencies, version bump to 0.1.7

### PR DESCRIPTION
**Pull request by medfreeman**

### CODE REVIEW

**Comment by Kristinita** [comment]
@fahad19 , please, review this pull-request.

Thanks.

**Comment by fahad19** [comment]
@Kristinita: I don't maintain this project any more. would you like it if I add you as a maintainer in this repository, and also add you to the package on npm?

**Comment by Kristinita** [comment]
@fahad19 , I'm not Node.js programmer 😿 . I may test glob-run pull requests and approve/decline it, but I may approve unexpected changes.

Maybe @medfreeman agree to be maintainer?

Thanks.

**Comment by lkulbacki** [comment]
+1 for the merge request. Not node.js programmer either (yet).

**Comment by fahad19** [comment]
@mojoaxel: thanks a lot for volunteering!

you have been added on both GitHub and npm.

**Comment by mojoaxel** [comment]
@fahad19 No problem, glad I can help. Will have a look at open pull-requests tomorrow and make a new release soon :rocket:

**Pull request merged**
